using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aether.DemoTool
{
    /// <summary>
    /// This can be expanded and taylored to customers specific needs
    /// </summary>
    public class PIPinfo
    {

        #region Constants
        public const string TERMINATOR = "\r\n";                                                        //I'LL BE BACK
        public const string COMMA = ",";                                                                //WAIT...
        public const string SPACE = " ";                                                                //THE FINAL FRONTIER
        public const string TAB = "\t ";                                                                //RUN ONE UP
        public const string UNDEFINED = "UNDEFINED";                                                    //UNKOWN
        public const double EMPTY = double.NaN;                                                         //MMMM BREAD
        public const int ZERO = 0;
        public const char BLANK = ' ';
        #endregion


        #region Properties
        private int partNumber;
        /// <summary>
        /// Customer Part number 
        /// </summary>
        public int PartNumber
        {
            get { return partNumber; }
            set { partNumber = value; }
        }

        private int operationNumber;
        /// <summary>
        /// Each part number may have multiple operations, and each opperation could require a unique PIP, or they could refer to the same PIP 
        /// </summary>
        public int OperationNumber
        {
            get { return operationNumber; }
            set { operationNumber = value; }
        }
        private string pipName;
        /// <summary>
        /// Uniquie file name for each .ztws 
        /// </summary>
        public string PipName
        {
            get { return pipName; }
            set { pipName = value; }
        }

        private string image;
        /// <summary>
        /// Image preview of PIP
        /// either auto generated by workspace, or by programmer
        /// </summary>
        public string Image
        {
            get { return image; }
            set { image = value; }
        }


        #endregion



        internal PIPinfo()
        {
            Initialize();
        }
        internal PIPinfo(int partNumber, int operationNumber)
        {

        }
        /// <summary>
        /// Clear and initialize
        /// </summary>
        internal void Initialize()
        {
            //Add default values here
        }



        PIPinfo(int partNumber, int operationNumber, string pipName, string imageName)
        {
            PartNumber = partNumber;
            OperationNumber = operationNumber;
            PipName = pipName;
            Image = imageName;
        }
        public static List<PIPinfo> PIPinfos()
        {
            List<PIPinfo> pipInfos = new List<PIPinfo>();

            pipInfos.Add(new PIPinfo(716246522, 400, @"exampleDrive\PIPforLAMpart_OPP400.ztws", @"\\dwffs08\ToolNet\ZeroTouch\Correlation\Pictures\All_ISO_HeatMap.PNG"));
            pipInfos.Add(new PIPinfo(556423, 250, @"exampleDrive\PIPforThispart_OPP250.ztws", @"\\dwffs08\ToolNet\ZeroTouch\Correlation\Pictures\All_ISO.PNG"));
            pipInfos.Add(new PIPinfo(8555, 10, @"exampleDrive\PIPfor8555art_OPP10.ztws", @"\\dwffs08\ToolNet\ZeroTouch\Correlation\Pictures\All_ISO_NoCAD.PNG"));
            pipInfos.Add(new PIPinfo(8555, 20, @"exampleDrive\PIPfor8555part_OPP20.ztws", @"\\dwffs08\ToolNet\ZeroTouch\Correlation\Pictures\Laser_ISO.PNG"));



            return pipInfos;
        }
    }
}
